In [1]:
### Imports ###
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard
from keras.engine.topology import Network
from keras.layers import *
from keras.models import Model
from keras.preprocessing import image
import keras.backend as K

import matplotlib.pyplot as plt

import numpy as np
import os
import random
import scipy.misc
from tqdm import *

%matplotlib inline

Using TensorFlow backend.


In [2]:
### Constants ###
DATA_DIR = "C:/Users/Chanchal/FINAL PROJECT LEARNINGS/data_new"
TRAIN_DIR = os.path.join(DATA_DIR, "train")
TEST_DIR = os.path.join(DATA_DIR, "test")

IMG_SHAPE = (64, 64)

In [3]:
def load_dataset_small(num_images_per_class_train=10, num_images_test=500):
    """Loads training and test datasets, from Tiny ImageNet Visual Recogition Challenge.

    Arguments:
        num_images_per_class_train: number of images per class to load into training dataset.
        num_images_test: total number of images to load into training dataset.
    """
    X_train = []
    X_test = []
    
    # Create training set.
    for c in os.listdir(TRAIN_DIR):
        c_dir = os.path.join(TRAIN_DIR, c, 'images')
        c_imgs = os.listdir(c_dir)
        random.shuffle(c_imgs)
        for img_name_i in c_imgs[0:num_images_per_class_train]:
            img_i = image.load_img(os.path.join(c_dir, img_name_i))
            x = image.img_to_array(img_i)
            X_train.append(x)
    random.shuffle(X_train)
    
    # Create test set.
    test_dir = os.path.join(TEST_DIR, 'images')
    test_imgs = os.listdir(test_dir)
    random.shuffle(test_imgs)
    for img_name_i in test_imgs[0:num_images_test]:
        img_i = image.load_img(os.path.join(test_dir, img_name_i))
        x = image.img_to_array(img_i)
        X_test.append(x)

    # Return train and test data as numpy arrays.
    return np.array(X_train), np.array(X_test)

In [4]:
# Load dataset.
X_train, X_test = load_dataset_small()

# Normalize image vectors.
#X_train = X_train_orig/255.
#X_test = X_test_orig/255.

# Print statistics.
print ("Number of training examples = " + str(X_train.shape[0]))
print ("Number of test examples = " + str(X_test.shape[0]))
print ("X_train shape: " + str(X_train.shape)) # Should be (train_size, 64, 64, 3).

Number of training examples = 2000
Number of test examples = 500
X_train shape: (2000, 64, 64, 3)


In [6]:
# We split training set into two halfs.
# First half is used for training as secret images, second half for cover images.

# S: secret image
input_S = X_train[0:X_train.shape[0] // 2]
print ("Number of secret images = " + str(input_S.shape[0]))
# C: cover image
input_C = X_train[X_train.shape[0] // 2:]
print ("Number of cover images = " + str(input_C.shape[0]))

Number of secret images = 1000
Number of cover images = 1000


In [7]:
input_S.shape

(1000, 64, 64, 3)

In [97]:
a = input_S
b = a.astype(int)

In [101]:
b[0].shape
digits = [int(c) for c in str(b[0])]

ValueError: invalid literal for int() with base 10: '['

In [98]:
print(b.shape)

(1000, 64, 64, 3)


In [55]:
arr = []
for i in range(0,flatten.shape[0]):
    c = np.binary_repr(flatten[i], width=8)
    arr.append(c)
    array = np.array(arr)

In [57]:
len(array)
print(array)

['10111100' '11010110' '11001001' ... '11100000' '11110011' '11111001']


In [ ]:
a = []
c = []
d = []
e =[]
for i in range(0,b.shape[0]):
    for j in range(0,b.shape[1]):
        for k in range(0,b.shape[2]):
            for l in range(0,b.shape[3]):
                s = b[i][j][k][l]
                dd = np.binary_repr(s, width=8)
                n = []
                for m in range(0,4):
                    o = dd[m]
                    n.append(o)
                ar = np.array(n)
                a.append(ar)
            arr = np.array(a)
            c.append(arr)
        arrr = np.array(arr)
        d.append(arrr)
    ar4 = np.array(d)
    e.append(ar4)
ar5 = np.array(e)

E:\App\lib\site-packages\ipykernel_launcher.py:21: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [63]:
print(b)

['1' '0' '1' ... '1' '1' '1']


In [67]:
c = array[0]
d = digits = [int(c) for c in str(c)]

In [68]:
print(d)

[1, 0, 1, 1, 1, 1, 0, 0]


In [72]:
n = []
for i in range(0,4):
    m = d[i]
    n.append(m)
print(n)

[1, 0, 1, 1]


In [73]:
ar = np.array(n)
print(ar)

[1 0 1 1]


In [85]:
data = input_S[0]
data = np.array(data)

In [86]:
extracted = (data[...,0] ^ data[...,1] ^ data[...,2])

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [103]:
input_S[0][0][0]

array([188., 214., 201.], dtype=float32)

In [109]:
a = []
for l in range(0,b.shape[3]):
    s = b[l]
    print(b[l])
    digits = [int(c) for c in str(s)]
    n = []
    for m in range(0,4):
        o = digits[m]
        n.append(o)
    ar = np.array(n)
    a.append(ar)
arr = np.array(a)

[[[188 214 201]
  [197 218 219]
  [225 236 255]
  ...
  [255 253 250]
  [255 250 248]
  [255 248 247]]

 [[195 202 194]
  [210 218 221]
  [222 227 247]
  ...
  [255 254 250]
  [255 251 248]
  [255 249 247]]

 [[204 183 182]
  [221 208 215]
  [226 223 240]
  ...
  [254 255 250]
  [255 253 248]
  [255 250 247]]

 ...

 [[157 141 141]
  [159 145 144]
  [160 149 147]
  ...
  [242 243 245]
  [242 247 253]
  [239 248 255]]

 [[159 138 135]
  [160 141 137]
  [160 145 140]
  ...
  [237 246 245]
  [231 245 248]
  [235 250 255]]

 [[160 135 130]
  [161 138 132]
  [161 142 136]
  ...
  [236 248 246]
  [222 237 242]
  [224 243 249]]]


ValueError: invalid literal for int() with base 10: '['

In [120]:
bb = b[0][0][0][0]
digits = [int(c) for c in str(bb)]
dd = np.binary_repr(digits, width=8)
print(dd)
for m in range(0,4):
        o = dd[m]

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
bb = b[0][0][0][0]
digits = [int(c) for c in str(bb)]
d = int(str(digits))
dd = np.binary_repr(d, width=8)

In [128]:
print(

[]
